name: clustermanager-runbookhub
desc: this is the demo clustermanager hum
runbooks:
- name: book-1
  desc: book describe
  selectors:
  - type: labelSelector
    selector: app=clustermanager
  - type: labelSelector
    selector: app-id=appsab909ba8cbe61c46e1cb3f9c4dffd24b038a
  - type: labelSelector
    selector: family=servicegroup
  - type: labelSelector
    selector: name=clustermanager
  - type: labelSelector
    selector: pod-template-hash=68d975bfc5
  - type: labelSelector
    selector: released-by=gopaddle
  - type: labelSelector
    selector: servicegroup=clustermanager-lee5js63
  - type: labelSelector
    selector: servicetype=gopaddle
  - type: jsonPathSelector
    selector: '{.apiVersion}=v1'
  - type: jsonPathSelector
    selector: '{.kind}=Pod'
  - type: jsonPathSelector
    selector: '{.metadata.name}=clustermanager-68d975bfc5-2mb5l'
  - type: jsonPathSelector
    selector: '{.metadata.namespace}=gopaddle'
  doc: clustermanager.md
